/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.1 and DSP System Toolbox 25.1.
 * Generated on: 24-Feb-2026 15:43:53
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : single
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2025a/extern/include/tmwtypes.h 
 */
#define MWSPT_NSEC 11
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real32_T NUM[MWSPT_NSEC][3] = {
  {
     0.2201719433,              0,              0 
  },
  {
                1,              2,              1 
  },
  {
     0.1794472188,              0,              0 
  },
  {
                1,              2,              1 
  },
  {
     0.1550510228,              0,              0 
  },
  {
                1,              2,              1 
  },
  {
     0.1411126405,              0,              0 
  },
  {
                1,              2,              1 
  },
  {
     0.1347445101,              0,              0 
  },
  {
                1,              2,              1 
  },
  {
                1,              0,              0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1 };
const real32_T DEN[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,  -0.8806877732,   0.7613754869 
  },
  {
                1,              0,              0 
  },
  {
                1,  -0.7177888751,   0.4355777502 
  },
  {
                1,              0,              0 
  },
  {
                1,  -0.6202040911,   0.2404082119 
  },
  {
                1,              0,              0 
  },
  {
                1,   -0.564450562,   0.1289011538 
  },
  {
                1,              0,              0 
  },
  {
                1,  -0.5389780402,  0.07795605808 
  },
  {
                1,              0,              0 
  }
};
